config/routes.rb
Rails.application.routes.draw do

  root 'generators#index'

  controller :admin do
    get 'admin' => :index
    get 'jobs' => :jobs
    get 'show_users' => :show_users
    get 'show_mechanical_props' => :show_mechanical_props
  end

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    post 'logout' => :destroy
  end

  resources :mechanical_props
  resources :users
  resources :generators
  resources :admin
end

app/models/generator.rb
class Generator < ApplicationRecord

  validates :a_vol,
            :b_vol,
            :c_vol,
            :d_vol,
            :email,
            :first_name,
            :last_name,
            presence: true

  validates_length_of :note, :maximum => 250
end

app/controllers/generators_controller.rb
class GeneratorsController < ApplicationController
  before_action :set_generator, only: [:show, :edit, :update, :destroy]
  skip_before_action :authorize, only: [:create, :show, :new, :index]

  # GET /generators
  # GET /generators.json
  def index
    @generators = Generator.all
  end

  # GET /generators/1
  # GET /generators/1.json
  def show
  end

  # GET /generators/new
  def new
    @generator = Generator.new
  end

  # GET /generators/1/edit
  def edit
  end

  # POST /generators
  # POST /generators.json
  def create
    @generator = Generator.new(generator_params)

    respond_to do |format|
      if @generator.save
        format.html { redirect_to @generator, notice: 'Data was successfully submitted.' }
        format.json { render :show, status: :created, location: @generator }
        sent_to_worker(@generator)
      else
        format.html { render :new }
        format.json { render json: @generator.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /generators/1
  # PATCH/PUT /generators/1.json
  def update
    respond_to do |format|
      if @generator.update(generator_params)
        format.html { redirect_to @generator, notice: 'Data was successfully updated.' }
        format.json { render :show, status: :ok, location: @generator }
      else
        format.html { render :edit }
        format.json { render json: @generator.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /generators/1
  # DELETE /generators/1.json
  def destroy
    @generator.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: 'Data was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_generator
    @generator = Generator.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def generator_params
    params.require(:generator).permit(:a_vol, :b_vol, :c_vol, :d_vol, :email, :first_name, :last_name, :note)
  end

  def sent_to_worker(params)
    job_container = {
        :id => params[:id],
        :parameter_1 => params[:a_vol],
        :parameter_2 => params[:b_vol],
        :parameter_3 => params[:c_vol],
        :parameter_4 => params[:d_vol],
        :email => params[:email],
        :first_name => params[:first_name],
        :last_name => params[:last_name],
        :note => params[:note],
        :created_at => params[:created_at],
        :updated_at => params[:updated_at]
    }

    HardWorker.perform_async(job_container)
  end
end

app/helpers/generators_helper.rb
module GeneratorsHelper
end

app/views/generators/_form.html.erb
<div style="margin-top: 20px;">
  <%= form_with(model: generator, local: true) do |form| %>
    <% if generator.errors.any? %>
      <div id="error_explanation" class="container text-center">
        <h2><%= pluralize(generator.errors.count, "error") %> prohibited this generator from being saved:</h2>

        <ul>
        <% generator.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <div class="container" style="padding: 300px; padding-bottom: 0; padding-top: 0">
        <h5>Variables:</h5>
        <div class="field">
          <%= form.text_field :a_vol, id: :generator_a_vol, class: "form-control", placeholder: :a_vol %>
        </div>

        <div class="field">
          <%= form.text_field :b_vol, id: :generator_b_vol, class: "form-control", placeholder: :b_vol %>
        </div>

        <div class="field">
          <%= form.text_field :c_vol, id: :generator_c_vol, class: "form-control", placeholder: :c_vol %>
        </div>

        <div class="field">
          <%= form.text_field :d_vol, id: :generator_d_vol, class: "form-control", placeholder: :d_vol %>
        </div>
      </div>
    </div>

    <div class="form-group">
      <div class="container" style="padding: 300px; padding-top: 0; padding-bottom: 0">
        <h5>Contact Information:</h5>
        <div class="field">
          <%= form.text_field :email, id: :generator_email, class: "form-control", placeholder: :email %>
        </div>

        <div class="field">
          <%= form.text_field :first_name, id: :generator_first_name, class: "form-control", placeholder: :first_name %>
        </div>

        <div class="field">
          <%= form.text_field :last_name, id: :generator_last_name, class: "form-control", placeholder: :last_name %>
        </div>
      </div>
    </div>

    <div class="form-group mt-5">
      <div class="field">
        <div class="container">
          <%= form.text_area :note, id: :generator_note, rows: 5, cols: 60, class:"form-control", placeholder: :note %>
        </div>
      </div>
    </div>

    <div class="actions" style="padding-top: 20px;">
      <button class="btn btn-success btn-lg btn-block" type="submit" value="Create Generator" data-disable-with="Create Generator" name="commit">Send</button>
    </div>
  <% end %>
</div>

app/views/generators/edit.html.erb
<div class="container">
  <h1 class="display-4 text-center">Editing Generator</h1>

  <%= render 'form', generator: @generator %>

  <%= link_to 'Show', @generator, class: "btn btn-secondary btn-lg btn-block", style: "color: white;" %>
  <%= link_to 'Back', jobs_path, class: "btn btn-secondary btn-lg btn-block", style: "color: white;"  %>
</div>

app/views/generators/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container text-center">
  <h1 class="display-4">Spot Weld Hub</h1>
  <%= image_tag("main_image.jpg", :alt => "main_img") %>
  <br>
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
  <%= link_to 'Local Constitutive Properties', new_mechanical_prop_path, class: "btn btn-success btn-lg btn-block", style: "color: white"%>
  <%= link_to 'Weld Deformation and Failure Behavior', new_generator_path, class: "btn btn-success btn-lg btn-block", style: "color: white"%>
</div>

<br>

app/views/generators/new.html.erb
<div class="container">
  <h1 class="display-4 text-center">Add variables for calculation:</h1>
  <p class="text-center mb-5">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

  <%= render 'form', generator: @generator%>

  <% if session[:user_id] %>
    <%= link_to 'Back', admin_path, class: "btn btn-secondary btn-lg btn-block", style: "color: white;" %>
  <% else %>
    <%= link_to 'Back', generators_path, class: "btn btn-secondary btn-lg btn-block", style: "color: white;" %>
  <% end %>
</div>

app/views/generators/show.html.erb
<div class="container text-center mt-5" style="border: 1px solid black">
  <div class="container text-center">
    <p id="notice"><%= notice %></p>
  </div>

  <p class="display-4">
    <%= @generator.id %>
  </p>

  <p class="display-4">
    <%= @generator.status = 'In process' %> <!-- UPDATE WITH A REAL STATUS FORM CONTROLLER-->
  </p>


  <p>
    <strong>A vol:</strong>
    <%= @generator.a_vol %>
  </p>

  <p>
    <strong>B vol:</strong>
    <%= @generator.b_vol %>
  </p>

  <p>
    <strong>C vol:</strong>
    <%= @generator.c_vol %>
  </p>

  <p>
    <strong>D vol:</strong>
    <%= @generator.d_vol %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= @generator.email %>
  </p>

  <p>
    <strong>First name:</strong>
    <%= @generator.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= @generator.last_name %>
  </p>

  <p>
    <strong>Note:</strong>
    <%= @generator.note %>
  </p>

  <%= link_to 'Edit', edit_generator_path(@generator), class: "btn btn-success btn-lg btn-block", style: "color: white" %>
  <%= link_to 'Back', jobs_path, class: "btn btn-secondary btn-lg btn-block", style: "color: white" %>
</div>