config/routes.rb
Rails.application.routes.draw do

  root 'generators#index'

  controller :admin do
    get 'admin' => :index
    get 'jobs' => :jobs
    get 'show_users' => :show_users
    get 'show_mechanical_props' => :show_mechanical_props
  end

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    post 'logout' => :destroy
  end

  resources :mechanical_props
  resources :users
  resources :generators
  resources :admin
end

app/views/admin/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>
  <div class="h2">Welcome to the Admin Site</div>
  <div>  <%= Time.now %></div>
  <hr>

  <div class="container" style="margin-top: 30px; margin-bottom: 25px;">
    <h5>Actions:</h5>
    <div>
      <%= link_to 'Mechanical', new_mechanical_prop_path %>
    </div>

    <div>
      <%= link_to 'Weld Strength', new_generator_path %>
    </div>

    <div>
      <%= link_to 'Create New Admin User', new_user_path %>
    </div>

    <h5 style="padding-top: 20px;">Data:</h5>
    <div>
      <%= link_to 'All Jobs Done', jobs_path %>
    </div>

    <div>
      <%= link_to 'Mechanical Props', show_mechanical_props_path %>
    </div>

    <div>
      <%= link_to 'Users', show_users_path %>
    </div>
  </div>
</div>

app/views/admin/jobs.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
  <div class="display-5">Jobs submitted:</div>
  <table style="border: 1px solid black; width: 100%;">
    <thead>
    <tr>
      <th>ID</th>
      <th>A vol</th>
      <th>B vol</th>
      <th>C vol</th>
      <th>D vol</th>
      <th>Email</th>
      <th>First name</th>
      <th>Last name</th>
      <th>Note</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
    <% @generators.each do |generator| %>
      <tr style="border: 1px solid black">
        <td><%= generator.id %></td>
        <td><%= generator.a_vol %></td>
        <td><%= generator.b_vol %></td>
        <td><%= generator.c_vol %></td>
        <td><%= generator.d_vol %></td>
        <td><%= generator.email %></td>
        <td><%= generator.first_name %></td>
        <td><%= generator.last_name %></td>
        <td><%= generator.note %></td>
        <td><% generator.status %></td>
        <td><%= link_to 'Show', generator %></td>
        <td><%= link_to 'Edit', edit_generator_path(generator) %></td>
        <td><%= link_to 'Destroy', generator, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
  <%= will_paginate @generators %>
  <%= link_to 'Back', admin_path, class: "btn btn-secondary btn-lg btn-block", style: "color: white; margin-top: 20px;" %>
</div>

app/views/admin/show_mechanical_props.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
  <div class="display-5">Mechanical Props:</div>
  <table style="border: 1px solid black; width: 100%;">
    <thead>
    <tr>
      <th>ID</th>
      <th>Carbon</th>
      <th>Structure</th>
      <th>Hardness (HV)</th>
      <th>Proof Yield Stress (MPa)</th>
      <th>Tensile Stress (MPa)</th>
      <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
    <% @mechanical_props.each do |mechanical_prop| %>
      <tr style="border: 1px solid black">
        <td><%= mechanical_prop.id %></td>
        <td><%= mechanical_prop.carbon %></td>
        <td><%= mechanical_prop.structure %></td>
        <td><%= mechanical_prop.hardness_hv %></td>
        <td><%= mechanical_prop.proof_yield_stress %></td>
        <td><%= mechanical_prop.tensile_stress %></td>
        <td><%= link_to 'Show', mechanical_prop %></td>
        <td><%= link_to 'Edit', edit_mechanical_prop_path(mechanical_prop) %></td>
        <td><%= link_to 'Destroy', mechanical_prop, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
  <%= will_paginate @mechanical_props %>
  <%= link_to 'Back', admin_path, class: "btn btn-secondary btn-lg btn-block", style: "color: white; margin-top: 20px;" %>
</div>

app/views/admin/show_users.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
  <div class="display-5 text-center">Users:</div>
  <table class="mx-auto col-sm-4" style="border: 1px solid black;">
    <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
    <% @users.each do |user| %>
      <tr style="border: 1px solid black">
        <td><%= user.name %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
  <%= link_to 'Back', admin_path, class: "btn btn-secondary btn-lg btn-block", style: "color: white; margin-top: 20px;" %>
</div>